name: get idiosyncrasy

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    environment:
      name: idiosyncrasy
      
    steps:
      - name: Checkout work repository
        uses: actions/checkout@v4
        with:
          repository: k7t3/widios
          path: ./widios
          ssh-key: ${{ secrets.REPO_KEY }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: gradle-cache-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-cache-${{ runner.os }}-

      - name: Restore backend-cli cache
        uses: actions/cache/restore@v4
        id: backend-cli-cache
        with:
          path: ./widios/backend-cli/.cache
          key: backend-cli-cache-${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            backend-cli-cache-${{ runner.os }}-

      - name: Verify Gradle
        run: ./gradlew --version
        working-directory: ./widios
      
      - name: run idiosyncrasy
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          GOOGLE_CLOUD_PROJECT: ${{ secrets.GOOGLE_CLOUD_PROJECT }}
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
          GH_MODEL_TOKEN: ${{ secrets.GH_MODEL_TOKEN }}
          DISABLE_TOPICS_DETECTION: ${{ vars.DISABLE_TOPICS_DETECTION }}
        run: |
          ./gradlew :backend-cli:run \
            -DYOUTUBE_API_KEY="$YOUTUBE_API_KEY" \
            -DGOOGLE_CLOUD_PROJECT="$GOOGLE_CLOUD_PROJECT" \
            -DGOOGLE_APPLICATION_CREDENTIALS_JSON="$GOOGLE_APPLICATION_CREDENTIALS_JSON" \
            -DGH_MODEL_TOKEN="$GH_MODEL_TOKEN" \
            -DDISABLE_TOPICS_DETECTION="$DISABLE_TOPICS_DETECTION"
        working-directory: ./widios

      - name: Save backend-cli cache
        uses: actions/cache/save@v4
        with:
          path: ./widios/backend-cli/.cache
          key: ${{ steps.backend-cli-cache.outputs.cache-primary-key }}
