name: get idiosyncrasy

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    environment:
      name: idiosyncrasy
      
    steps:
      - name: Checkout work repository
        uses: actions/checkout@v4
        with:
          repository: k7t3/widios
          path: ./widios
          ssh-key: ${{ secrets.REPO_KEY }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-cache-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-cache-${{ runner.os }}-

      - name: Verify Gradle
        run: ./gradlew --version
        working-directory: ./widios
      
      - name: run idiosyncrasy
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          GOOGLE_CLOUD_PROJECT: ${{ secrets.GOOGLE_CLOUD_PROJECT }}
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          ./gradlew :backend-cli:run \
            -DYOUTUBE_API_KEY="$YOUTUBE_API_KEY" \
            -DGOOGLE_CLOUD_PROJECT="$GOOGLE_CLOUD_PROJECT" \
            -DGOOGLE_APPLICATION_CREDENTIALS_JSON="$GOOGLE_APPLICATION_CREDENTIALS_JSON" \
            -DGEMINI_API_KEY="$GEMINI_API_KEY"
        working-directory: ./widios
